import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRight,
  faBars,
  faBookmark as faBookmarkSolid,
  faBoltLightning,
  faCalendarDays,
  faChartLine,
  faChartSimple,
  faCaretLeft,
  faCaretRight,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCheck,
  faCloudRain,
  faCloudSun,
  faCloudArrowUp,
  faComment,
  faCompass,
  faCopy,
  faDownload,
  faExclamation,
  faFaceMeh,
  faFire,
  faGear,
  faHelmetSafety,
  faInfo,
  faIndustry,
  faInfinity,
  faLayerGroup,
  faLink,
  faLocationArrow,
  faLocationDot,
  faMap,
  faMinus,
  faPersonDigging,
  faPencil,
  faPlus,
  faReply,
  faSatellite,
  faScaleBalanced,
  faShareNodes,
  faSort,
  faSmog,
  faStopwatch,
  faTemperatureHigh,
  faTemperatureLow,
  faTimeline,
  faUser,
  faVolumeHigh,
  faWind,
  faXmark,
  faShareFromSquare,
  faTrash,
  faFloppyDisk,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBookmark as faBookmarkRegular,
  faComment as faCommentRegular,
  faNewspaper,
  faMap as faMapRegular,
  faCopy as faCopyRegular,
  faFileLines,
  faPenToSquare,
} from "@fortawesome/free-regular-svg-icons";
import { faXTwitter } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { faCreditCard } from "@fortawesome/free-regular-svg-icons";

library.add(
  faArrowRight,
  faBars,
  faBookmarkSolid,
  faBookmarkRegular,
  faBoltLightning,
  faCalendarDays,
  faChartLine,
  faChartSimple,
  faCaretLeft,
  faCaretRight,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCheck,
  faCloudRain,
  faCloudSun,
  faCloudArrowUp,
  faComment,
  faCommentRegular,
  faCompass,
  faCopy,
  faCopyRegular,
  faDownload,
  faInfo,
  faExclamation,
  faFaceMeh,
  faFire,
  faGear,
  faHelmetSafety,
  faIndustry,
  faInfinity,
  faLayerGroup,
  faLink,
  faLocationArrow,
  faLocationDot,
  faMap,
  faMapRegular,
  faMinus,
  faPersonDigging,
  faPencil,
  faPlus,
  faReply,
  faSatellite,
  faScaleBalanced,
  faShareNodes,
  faSort,
  faSmog,
  faStopwatch,
  faTemperatureHigh,
  faTemperatureLow,
  faTimeline,
  faUser,
  faVolumeHigh,
  faWind,
  faXmark,
  faShareFromSquare,
  faNewspaper,
  faFileLines,
  faPenToSquare,
  faTrash,
  faFloppyDisk,
  faXTwitter,
  faCreditCard
);

export function useIcons(app) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
