import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRight,
  faBars,
  faBookmark as faBookmarkSolid,
  faBoltLightning,
  faCaretLeft,
  faCaretRight,
  faCaretDown,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCheck,
  faCloudRain,
  faCloudSun,
  faCloudArrowUp,
  faComment,
  faCopy,
  faDownload,
  faFire,
  faGear,
  faHelmetSafety,
  faInfinity,
  faLink,
  faLocationArrow,
  faMessage,
  faMinus,
  faPencil,
  faPlus,
  faReply,
  faSatellite,
  faShareNodes,
  faSmog,
  faTemperatureHigh,
  faTemperatureLow,
  faTrash,
  faUser,
  faVolumeHigh,
  faWind,
  faXmark,
  faShareFromSquare,
  faFloppyDisk,
  faChartLine,
  faChartSimple,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBookmark as faBookmarkRegular,
  faComment as faCommentRegular,
  faNewspaper,
  faMap as faMapRegular,
  faCopy as faCopyRegular,
  faFileLines,
  faCreditCard,
} from "@fortawesome/free-regular-svg-icons";
import { faXTwitter } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faArrowRight,
  faBars,
  faBookmarkSolid,
  faBookmarkRegular,
  faBoltLightning,
  faCaretLeft,
  faCaretRight,
  faCaretDown,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCheck,
  faCloudRain,
  faCloudSun,
  faCloudArrowUp,
  faComment,
  faCommentRegular,
  faCopy,
  faCopyRegular,
  faDownload,
  faFire,
  faGear,
  faHelmetSafety,
  faInfinity,
  faLink,
  faLocationArrow,
  faMessage,
  faMapRegular,
  faMinus,
  faPencil,
  faPlus,
  faReply,
  faSatellite,
  faShareNodes,
  faSmog,
  faTemperatureHigh,
  faTemperatureLow,
  faTrash,
  faUser,
  faVolumeHigh,
  faWind,
  faXmark,
  faShareFromSquare,
  faFloppyDisk,
  faChartLine,
  faChartSimple,
  faNewspaper,
  faFileLines,
  faXTwitter,
  faCreditCard
);

export function useIcons(app) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
